/// Flutter icons IconSet
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconSet
///      fonts:
///       - asset: fonts/IconSet.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconSet {
  IconSet._();

  static const _kFontFam = 'IconSet';
  static const String? _kFontPkg = null;

  static const IconData assignment_ind = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders_h = IconData(0xf1de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_badge = IconData(0xf2c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xf2c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
